[build]
  publish = "dist"
  command = "npm run build"

# 301 Redirects from .html to clean routes
[[redirects]]
  from = "/summarize.html"
  to = "/summarize"
  status = 301

[[redirects]]
  from = "/ask.html"
  to = "/ask"
  status = 301

[[redirects]]
  from = "/images.html"
  to = "/images"
  status = 301

[[redirects]]
  from = "/office.html"
  to = "/office"
  status = 301

[[redirects]]
  from = "/annotate.html"
  to = "/annotate"
  status = 301

[[redirects]]
  from = "/faq.html"
  to = "/faq"
  status = 301

[[redirects]]
  from = "/blog.html"
  to = "/blog"
  status = 301

[[redirects]]
  from = "/about.html"
  to = "/about"
  status = 301

[[redirects]]
  from = "/privacy.html"
  to = "/privacy"
  status = 301

[[redirects]]
  from = "/terms.html"
  to = "/terms"
  status = 301

# Static files (served directly)
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

# SPA fallback for React Router (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=86400"
